feat: new api for scripts

diff --git a/scripts/gui/br b/scripts/gui/br
--- a/scripts/gui/br
+++ b/scripts/gui/br
@@ -1,6 +1,6 @@
 #!/bin/sh
 
-. slib
+. "lib_common.sh"
 
 help() {
 cat << EOF
@@ -9,33 +9,25 @@ options:
 [link]           Open link
  -h              Print this message and exit
 
-NOTE: bookmarks file is located at ~/.config/sites/bookmarks
+NOTE: bookmarks file is located at ~/.config/sites/bookmarks.txt
 EOF
-
 exit 0
 }
 
-alias dmenucmd="dmenu -bw 1 -c -g 1 -l 25"
-
-[ -z "${BROWSER}" ] && browser="qutebrowser" || browser="${BROWSER}"
+[ -z "${BROWSER}" ] && BROWSER="firefox"
 
 if [ "${#}" -eq 0 ]; then
+	bookmark_path="${XDG_CONFIG_HOME:-$HOME/.config}/sites/bookmarks.txt"
+	[ -e "${bookmark_path}" ] || err "Couldn't find bookmarks file"
 
-	link_file="${XDG_CONFIG_HOME:-$HOME/.config}/sites/bookmarks.txt"
+	. "lib_handle.sh"
 
-	check_program "dmenu"
+	link=$(< "${bookmark_path}" menu_handle center)
 
-	[ -z "${XDG_HOME_CONFIG}" ] || link_file="${XDG_HOME_CONFIG}"/sites/bookmarks.txt
-	[ -e "${link_file}" ] || err "Couldn't find bookmarks file"
-
-	link=$(< "${link_file}" dmenucmd)
-
-	[ -z "${link}" ] || "${browser}" "${link}"
-
-elif [ "${#}" -eq 1 ]; then
-	[ "${1}" = "-h" ] && help
-
-	"${browser}" "${1}"
-else
-	invalid_use
+	[ -z "${link}" ] || "${BROWSER}" "${link}"
 fi
+
+[ "${#}" -ne 1 ] && invalid_use
+[ "${1}" = "-h" ] && help
+
+"${BROWSER}" "${1}"
diff --git a/scripts/gui/sclip b/scripts/gui/sclip
--- a/scripts/gui/sclip
+++ b/scripts/gui/sclip
@@ -1,71 +1,72 @@
 #!/bin/sh
 
-. slib
+. "lib_common.sh"
+. "lib_handle.sh"
 
 help() {
 cat << EOF
-${0}: print the clipboard content
+${progname}: print the clipboard content
 options:
- -h              Print this message and exit
  -s              Do not send notifications
  -c [text]       Copy text to clipboard
  -f [file]       Copy content of file into clipboard
  -i              Copy standart input into clipboard
+ -h              Print this message and exit
 EOF
-
 exit 0
 }
 
-check_program "xclip"
+clipboard_handle check_program
 
-i_flg=0
+if [ "${#}" -eq 0 ]; then
+	clipboard_handle get-clipboard
+	exit $?
+fi
+
+read_stdin=0
 silent=0
 while getopts "f:c:sih" option; do
 	case "${option}" in
 	f) filepath="${OPTARG}" ;;
-
 	c) input="${OPTARG}" ;;
-
 	s) silent=1 ;;
-
-	i) i_flg=1 ;;
-
+	i) read_stdin=1 ;;
 	h) help ;;
 
 	*) invalid_use -h ;;
 	esac
 done
-
 shift $((OPTIND - 1))
 
 [ "${#}" -ne 0 ] && invalid_use
 
 if [ -n "${filepath}" ]; then
-	mime_type=$(file --mime-type -b "${filepath}")
+	mime_type=$(file_handle get-mime_type "$filepath") || {
+		err "Failed to detect mime type"; exit 1;}
 
-	if [ "${silent}" -eq 1 ]; then
-		run "xclip -selection clipboard -t ${mime_type} -i ${filepath}"
-	fi
+	clipboard_handle file "${mime_type}" "${filepath}"
+	status=$?
 
-	run --success-notify "${filepath} copied" \
-		--failure-notify "${filepath} failed to copy" \
-		"xclip -selection clipboard -t ${mime_type} -i ${filepath}"
+else
+	[ -z "$input" ] && [ "$read_stdin" -eq 1 ] && input=$(cat)
+	[ -z "$input" ] && err "Empty input"
+
+	printf '%s' "${input}" | clipboard_handle text
+	status=$?
 fi
 
-[ "${i_flg}" -eq 1 ] && input=$(cat)
-
-if [ -n "${input}" ]; then
-	# Don't use `run` since pipes are used
-	printf '%s' "${input}" | xclip -selection clipboard
-
-	if [ $? -eq 0 ]; then
-		[ "${silent}" -eq 0 ] && send_notification "${argv0}:" "'${input}' copied"
-		exit 0
+if [ "${silent}" -eq 0 ]; then
+	if [ "${status}" -eq 0 ]; then
+		if [ -n "${filepath}" ]; then
+			notify_handle "Copied file: ${filepath}"
+		else
+			notify_handle "Copied text"
+		fi
+	else
+		if [ -n "${filepath}" ]; then
+			notify_handle "Failed to copy file: ${filepath}"
+		else
+			notify_handle "Failed to copy text"
+		fi
 	fi
-
-	[ "${silent}" -eq 0 ] && send_notification "${argv0}:" "'${input}' failed to copy"
-
-	exit 1
 fi
-
-run "xclip -o -selection clipboard"
